Add controllers
MityaDD/java-shareit pull request #1
Opened 2023-05-12 10:04 UTC by MityaDD

2023-05-13 07:30 UTC, Fleaman777 requested changes

2023-05-13 07:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NotNull // или проверять?
так хорошо

2023-05-13 07:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Неверный параметр: " + e.getMessage());
внутри лога лучше использовать плейсхолдер {}
и читаться будет лучше, и работать оптимальней

относится ко всем похожим местам

2023-05-13 07:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/ExceptionsHandler.java
> +public class ExceptionsHandler {
а есть смысл делать 2 класса с одинаковым функционалом ExceptionsHandler и ErrorHandler ?

2023-05-13 07:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String userIdHeader = "X-Sharer-User-Id";
эта переменная больше похожа на константу, 
можно ее сделать static и назвать в верхнем регистре

2023-05-13 07:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        List<ItemDto> items = itemService.getAllItemsByUserId(userId);
можно не создавать отдельную переменную для результата, 
по сути она используется только в 1 месте, где можно сразу сделать itemService.getAllItemsByUserId(userId)

аналагично в похожих моментах, где созданная локальная перменная используется только в 1 месте

2023-05-13 07:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                        && u.getId() != user.getId())) {
условие будет лучше восприниматься, если этот стрим вынести в отдельный метод с подходящим названием

2023-05-13 07:44 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/exception/ExceptionsHandler.java
> +public class ExceptionsHandler {
Остались артефакты от экспериментов) Моя вина, не почистил перед ревью.
Исправил.

2023-05-13 07:46 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String userIdHeader = "X-Sharer-User-Id";
Сделал.

2023-05-13 07:50 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Неверный параметр: " + e.getMessage());
Сделал.

2023-05-13 08:05 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        List<ItemDto> items = itemService.getAllItemsByUserId(userId);
Решил немного усложнить контроллеры, чтобы хоть чем-то проект отличался от filmorate. Согласен, что баловство и некрасиво.
Убрал лишний обвес.

2023-05-13 08:19 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                        && u.getId() != user.getId())) {
Согласен. Исправил.

2023-05-13 08:31 UTC, MityaDD commented
Сделал все рекомендуемые исправления. Благодарю за предложение обращаться с вопросами. 
Пока что всё понятно и легко, но по следующему спринту, где будет работа с БД, я соберу вопросы и
напишу в Пачку.

2023-05-13 10:27 UTC, MityaDD commented
Добавил пропущенные логи, сделал читабельнее метод isEmailAlreadyRegistered.
На ревью.

2023-05-14 07:33 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        List<ItemDto> items = itemService.getAllItemsByUserId(userId);
еще будут спринты, что бы это приложение отличалось от фильморейта))

к тому же контроллеры, очень часто между собой похожи, в основном их отличие в название методов

2023-05-14 07:34 UTC, Fleaman777 approved these changes

2023-05-21 10:01 UTC, merged