Add bookings
MityaDD/java-shareit pull request #2
Opened 2023-06-02 19:21 UTC by MityaDD

2023-06-03 11:53 UTC, Fleaman777 requested changes

2023-06-03 11:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                         @RequestParam("approved") boolean approved,
можно не указывать значение для name параметра, если оно совпадает с названием аргумента метода

2023-06-03 11:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (booking.getStatus().equals(Status.APPROVED)) {
енамы хорошо сравнивать через == 
так и сравнивается быстрее, и выглядит чуть очевидней

аналагично в др местах

2023-06-03 11:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private static final LocalDateTime NOW = LocalDateTime.now();
не стоит текущую дату выносить в константу, лучше оставить ее в методе
помню как-то на работе немного обжегся на этом) 

проблема в том, что когда приложение соберется и поставится на сервер, эта переменная создастся и будет неизменной все остальное время, пока приложение не перегрузится, а это может быть дни, недели....

2023-06-03 11:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    @Query("select b " +
мелочь, но тем не менее
select тоже можно написать в верхнем регистре, что бы стиль ключевых слов в запросе был одинаковым

2023-06-03 11:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +            "ORDER BY b.start DESC ")
о, а здесь все супер

2023-06-03 11:53 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    // Collection<Item> findItemsByOwnerId(long ownerId);
есть такой антипаттер "мертвый код"
если код не используется, то можно его удалить, 
высока вероятность, что он долго так будет висеть. 

А если вдруг он нам все же понадобится, то всегда можно обратиться к гит истории

2023-06-05 13:36 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private static final LocalDateTime NOW = LocalDateTime.now();
Я уже столкнулся с этой ошибкой, когда использовал константу NOW для методов getBookingsList. Там тоже требуется LocalDateTime.now(). И, разумеется, у меня тесты сыпались.  А вот с валидацией времени и даты прокатило. Но согласен, надо аккуратнее. Теперь понял почему. Исправил.

2023-06-05 13:46 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                         @RequestParam("approved") boolean approved,
Сделал

2023-06-05 13:46 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (booking.getStatus().equals(Status.APPROVED)) {
Сделал

2023-06-05 13:47 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    @Query("select b " +
Сделал

2023-06-05 13:47 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    // Collection<Item> findItemsByOwnerId(long ownerId);
Убрал закоментированное

2023-06-05 13:50 UTC, MityaDD commented
Учел все замечания.

2023-06-06 13:36 UTC, Fleaman777 approved these changes

2023-06-07 07:48 UTC, merged