Add item requests
MityaDD/java-shareit pull request #3
Opened 2023-06-10 20:03 UTC by MityaDD

2023-06-12 06:50 UTC, Fleaman777 requested changes

2023-06-12 06:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    List<ItemRequestDto> getAllRequestsByOtherUsers(Long userId, Integer from, Integer size);
а есть ли смысл делать from и size типа Integer, почему бы сразу не сделать int

2023-06-12 06:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    }
у Optional класса есть хороший метод orElseThrow 
отлично сюда впишется и сократит количество кода

2023-06-12 06:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .collect(Collectors.toList());
стрим в стриме, использующий стрим.._)
попробуй немного оптимизироват этот метод, что бы было меньше вариантов запутаться, 
как минимум, можно было бы часть логики вынести в отдельный метод

2023-06-12 06:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/storage/ItemRequestStorage.java
> +    //              findAllByRequesterIdIsNotOrderByCreatedDesc
эти клмментарии можно было бы убрать

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void getBookingById() throws Exception {
что бы при поиске метода по всему проекту на отвлекаться на тесты, лучше тесты называть иначе, чем методы основных классов,

например этот можно было бы назвать 
shouldReturnOkWhenGetBookingById 

из названия сразу понятно, что именно проверяется в тесте и при каких условиях

относится ко всем похожим местам

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", userId))
X-Sharer-User-Id в тестах так же можно было бы вынести в константу

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void shouldUpdateBookingWithSecondApproved() throws Exception {
вот тут хорошее название

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void shouldTrowEcsWhenUserUnknown() throws Exception {
посколько ты тестрируешь апи своего приложения, а оно наружу отдает не исключение, а конкретный error code, то лучше указывать именно его

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingDtoTest.java
> +        LocalDateTime start = LocalDateTime.now().withNano(000000);
а для чего нужно использовать этот метод с этими параметрами ? 
.withNano(000000)

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    void test_5_findAllByBookerIdAndStatusOrderByStartDesc() {
где-то есть упоминание номера теста, где-то нет, 

не совсем понятно, для чего оно тогда нужно, 
лучше не опираться на их порядок и количество, т.к. оно постоянно будет меняться, и в какой-то момент названия могут разъехаться с реальностью, что конечно будет сбивать

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    void findAllByOwnerIdAndStatusOrderByStartDesc() {
аналагично, название тестового метода не должно совпадать с названием основного

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +        Long userId = 1L;
почему бы не вынести userId в константу

2023-06-12 06:50 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceTest.java
> +        requestStorage.save(itemRequest1);
для создания Item и ItemRequest можно было бы создать отдельные вспомогательные методы, что бы в основном тестовом методу не дублировать их создание и добавление в БД

2023-06-12 07:10 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    }
Я знаю про этот метод. И у меня в коде ни одно такое место с Optional. Вообще вся затея с утилитарным классом для того, чтобы вместо двух строчек (throw exc + log ) писать одну Log.andThrowNotFound или Log.andThrowNotValid. На свой вкус оставлю как есть. Но если замечание критическое, то в следующей итерации поменяю везде.

2023-06-12 07:17 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void getBookingById() throws Exception {
На самом деле первоначально я так и сделал. Но в этом спринте изменили правила покрытия тестами, нужно 90% покрытие. Я не понимал, как это работает.При первом заливе ветки у меня было 80%, хотя я думал, что все 100% и не понимал, что от меня хочет алгоритм. Может быть, чтобы названия методов совпадало в тестах? все эти последние коммиты CheckStyle были попытками добить до 90%. 
Исправил.

2023-06-12 07:22 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/booking/BookingDtoTest.java
> +        LocalDateTime start = LocalDateTime.now().withNano(000000);
Помню в 14 спринте в одном из тестов постмана глюк с этим LocalDateTime.now(). Либо надо добавлять .withNano(000000), либо запускать всю коллекцию не по-блочно. В тестах не критично, согласен. исправил

2023-06-12 07:27 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    void test_5_findAllByBookerIdAndStatusOrderByStartDesc() {
Артефакты первого варианта. В этом блоке тестов есть повторяющиеся методы, отличие только в параметрах. Первоначально хотел под номерами. Исправил.

2023-06-12 07:29 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    void findAllByOwnerIdAndStatusOrderByStartDesc() {
Исправил

2023-06-12 07:34 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +        Long userId = 1L;
Согласен. Вынес в константу.

2023-06-12 07:44 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceTest.java
> +        requestStorage.save(itemRequest1);
Забыл или подустал уже от тестописания. Исправил, как надо.

2023-06-12 08:06 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", userId))
Исправил по всем классам.

2023-06-12 08:07 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    List<ItemRequestDto> getAllRequestsByOtherUsers(Long userId, Integer from, Integer size);
Исправил

2023-06-12 09:32 UTC, MityaDD commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .collect(Collectors.toList());
Сделал

2023-06-12 09:47 UTC, MityaDD commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void shouldTrowEcsWhenUserUnknown() throws Exception {
Сделал по всем классам тестов.

2023-06-12 10:02 UTC, MityaDD commented
Исправил все недочеты. На второе ревью.

2023-06-13 08:14 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    }
можно еще попробовать вариант, перезагрузить утилитарный класс и возвращать эксепшен, который можно было бы выбросить из Optional,

а так да, это не критично, можешь оставить как есть.

2023-06-13 08:15 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void getBookingById() throws Exception {
Да, есть такая вечная проблема, понять как анализатор считает покрытие ))

2023-06-13 08:17 UTC, Fleaman777 approved these changes

2023-06-13 08:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                        itemStorage.findItemsByRequestId(itemRequest.getId())
хорошее исправление

2023-06-13 08:17 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingStorageTest.java
> +    void shouldFindAllByBookerIdAndStatusOrderByStartDescREJECTED() {
Названия отличные

2023-06-13 08:39 UTC, merged